title = "VluxySoundFactory"
gitRepoUrl = "https://github.com/greenviper126/VluxySoundFactory"
gitSourceBranch = "master"
changelog = true

[docusaurus]
organizationName = "vlux"
projectName = "VluxySoundFactory"
deploymentBranch = "gh-pages"
tagline = "The extensible command console for Roblox developers"
titleDelimiter = "•"

url = "https://greenviper126.github.io"
baseUrl = "/TheLaundryShift/"

# TODO: Remove when releasing new website
noIndex = true

[home]
enabled = true
includeReadme = false
